package net.ntworld.sentryIntegrationIdea.serviceProvider.community

import net.ntworld.sentryIntegrationIdea.serviceProvider.ApplicationServiceProvider

interface ApplicationServiceProviderCommunity : ApplicationServiceProvider