package net.ntworld.sentryIntegrationIdea.serviceProvider.community

import net.ntworld.sentryIntegrationIdea.serviceProvider.ProjectServiceProvider

interface ProjectServiceProviderCommunity: ProjectServiceProvider